/**
 * Common English first names + surnames used to flag likely name tokens.
 *
 * This is intentionally compact – it covers the ~800 most common
 * first names (male + female) and ~200 most common surnames in
 * English-speaking countries. All lowercase for O(1) Set look-up.
 */

const RAW = [
  // ── Male first names ────────────────────────────────────────────────
  "james","john","robert","michael","david","william","richard","joseph",
  "thomas","charles","christopher","daniel","matthew","anthony","mark",
  "donald","steven","paul","andrew","joshua","kenneth","kevin","brian",
  "george","timothy","ronald","edward","jason","jeffrey","ryan","jacob",
  "gary","nicholas","eric","jonathan","stephen","larry","justin","scott",
  "brandon","benjamin","samuel","raymond","gregory","frank","alexander",
  "patrick","jack","dennis","jerry","tyler","aaron","jose","nathan",
  "henry","peter","douglas","zachary","adam","harold","kyle","noah",
  "gerald","ethan","carl","arthur","lawrence","dylan","jesse","jordan",
  "bryan","billy","bruce","eugene","ralph","roy","louis","russell",
  "bobby","philip","johnny","albert","wayne","randy","vincent","harry",
  "howard","eugene","freddie","roger","keith","stanley","leonard","ernest",
  "todd","craig","alan","shawn","clarence","sean","derek","travis",
  "luis","victor","elijah","caleb","mason","logan","owen","liam",
  "lucas","aiden","jackson","sebastian","mateo","oliver","carter","jayden",
  "luke","gabriel","leo","lincoln","hudson","theo","miles","cole",
  "connor","austin","isaac","landon","parker","asher","dominic","adrian",
  "christian","hunter","cam","cameron","levi","brayden","kai","max",
  "maxwell","blake","wyatt","tristan","easton","gavin","chase","ryder",
  "nolan","emmett","sawyer","jace","roman","axel","silas","beckett",
  "jaxon","maverick","weston","everett","tucker","hayes","finn","brody",
  "spencer","archer","cruz","rowan","riley","grayson","felix","grant",
  "jameson","brady","gage","zane","reed","tate","orion","dean",
  // ── Female first names ──────────────────────────────────────────────
  "mary","patricia","jennifer","linda","barbara","elizabeth","susan",
  "jessica","sarah","karen","lisa","nancy","betty","margaret","sandra",
  "ashley","dorothy","kimberly","emily","donna","michelle","carol",
  "amanda","melissa","deborah","stephanie","rebecca","sharon","laura",
  "cynthia","kathleen","amy","angela","shirley","anna","brenda","pamela",
  "emma","nicole","helen","samantha","katherine","christine","debra",
  "rachel","carolyn","janet","catherine","maria","heather","diane",
  "ruth","julie","olivia","joyce","virginia","victoria","kelly","lauren",
  "christina","joan","evelyn","judith","megan","andrea","cheryl","hannah",
  "jacqueline","martha","gloria","teresa","ann","sara","madison",
  "frances","kathryn","janice","jean","abigail","alice","judy","sophia",
  "grace","denise","amber","doris","marilyn","danielle","beverly",
  "isabella","theresa","diana","natalie","brittany","charlotte","marie",
  "kayla","alexis","lori","chloe","ariana","mia","skylar","haley",
  "allison","savannah","julia","mackenzie","kennedy","autumn","genesis",
  "adriana","gabriella","elena","bella","naomi","eleanor","maya",
  "madeline","aubrey","penelope","layla","riley","zoey","nora","lily",
  "lillian","quinn","ivy","aurora","claire","stella","lucy","caroline",
  "harper","scarlett","violet","eva","leah","piper","nova","emilia",
  "willow","ruby","ellie","isla","jade","vivian","daisy","paisley",
  "brooke","brielle","eden","ember","freya","iris","juniper","luna",
  "genevieve","margot","ana","tessa","vera","wren","fiona","keira",
  // ── Common surnames ─────────────────────────────────────────────────
  "smith","johnson","williams","brown","jones","garcia","miller","davis",
  "rodriguez","martinez","hernandez","lopez","gonzalez","wilson","anderson",
  "thomas","taylor","moore","jackson","martin","lee","perez","thompson",
  "white","harris","sanchez","clark","ramirez","lewis","robinson","walker",
  "young","allen","king","wright","scott","torres","nguyen","hill",
  "flores","green","adams","nelson","baker","hall","rivera","campbell",
  "mitchell","carter","roberts","gomez","phillips","evans","turner",
  "diaz","parker","cruz","edwards","collins","reyes","stewart","morris",
  "morales","murphy","cook","rogers","gutierrez","ortiz","morgan","cooper",
  "peterson","bailey","reed","kelly","howard","ramos","kim","cox",
  "ward","richardson","watson","brooks","chavez","wood","bennett","gray",
  "mendoza","ruiz","hughes","price","alvarez","castillo","sanders",
  "patel","myers","long","ross","foster","jimenez","powell","jenkins",
  "perry","russell","sullivan","bell","coleman","butler","henderson",
  "barnes","gonzales","fisher","vasquez","simmons","griffin","mcdonald",
  "hayes","murray","ford","graham","hamilton","shaw","wallace","woods",
  "cole","west","jordan","owens","reynolds","fisher","ellis","harrison",
  "gibson","mcdonald","alexander","wagner","tucker","burns","mason",
  "olson","hunt","hicks","palmer","duncan","armstrong","berry","lane",
  // ── Misc names that appear in novels ────────────────────────────────
  "tom","joe","bob","jim","ben","sam","dan","ted","ed","al","fred",
  "sue","meg","ann","eve","jane","kate","rose","beth","nell","bess",
  "dick","huck","pip","heathcliff","darcy","bennet","eyre","gatsby",
  "atticus","scout","jem","boo","holden","moriarty","sherlock","watson",
  "bilbo","frodo","gandalf","aragorn","legolas","gimli","sauron",
  "hermione","dumbledore","voldemort","severus","draco","hagrid",
  "katniss","peeta","gale","tyrion","cersei","daenerys","arya","sansa",
  "jaime","theon","stannis","brienne","joffrey","ramsay","samwell",
  "bran","hodor","oberyn","davos","varys","bronn","melisandre",
  "don","quixote","sancho","hester","prynne","ishmael","ahab",
  "raskolnikov","dmitri","aloysius","ebenezer","scrooge","oliver",
  "twist","fagin","pip","estella","havisham","jane","rochester",
  // ── Place-like words common in fiction ──────────────────────────────
  "london","paris","rome","york","boston","chicago","dublin","oxford",
  "cairo","vienna","tokyo","moscow","berlin","madrid","lisbon","naples",
  "florence","venice","milan","athens","prague","budapest","warsaw",
  "copenhagen","stockholm","oslo","helsinki","amsterdam","brussels",
  "shire","hogwarts","narnia","mordor","gondor","rivendell","westeros",
  "winterfell","asgard","gotham","metropolis","atlantis",
];

export const COMMON_NAMES = new Set<string>(RAW);
